CREATE TABLE brapi_CallSet (
  additionalInfo MAP < STRING,
  STRING > COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  callSetDbId STRING COMMENT 'The ID which uniquely identifies a CallSet within the given database server',
  callSetName STRING COMMENT 'The human readable name which identifies a germplasm within the given database server',
  created STRING COMMENT 'The date this call set was created',
  externalReferences ARRAY < STRUCT < referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
  referenceSource STRING COMMENT 'An identifier for the source system or database of this reference' > > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  sampleDbId STRING,
  sampleName STRING,
  samplePUI STRING COMMENT 'The Biosample entity the call set data was generated from.',
  studyDbId STRING,
  studyName STRING,
  studyPUI STRING COMMENT 'The ID which uniquely identifies a study within the given database server',
  updated STRING COMMENT 'The time at which this call set was last updated',
  -- Link table 'VariantSetByCallSet' will be created separately COMMENT 'The IDs of the variantSets this callSet has calls in.' )  COMMENT 'A CallSet is a collection of Calls that were generated by the same analysis of the same Sample' ;
  CREATE TABLE brapi_VariantSetByCallSet (
    variantSetDbId STRING,
    variantSetName STRING,
    callSetDbId STRING,
    callSetName STRING
  ) COMMENT 'Link table for CallSet to VariantSet on property variantSets';