CREATE TABLE brapi_Study (
  active BOOLEAN COMMENT 'A flag to indicate if a Study is currently active and ongoing',
  additionalInfo MAP < STRING,
  STRING > COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  commonCropName STRING COMMENT 'Common name for the crop associated with this study',
  -- For property 'contacts' Link table 'ContactByStudy' will be created separately,
  culturalPractices STRING COMMENT 'MIAPPE V1.1 (DM-28) Cultural practices - General description of the cultural practices of the study.',
  dataLinks ARRAY < STRUCT < dataFormat STRING COMMENT 'The structure of the data within a file. For example - VCF, table, image archive, multispectral image archives in EDAM ontology (used in Galaxy)  MIAPPE V1.1 (DM-38) Data file description - Description of the format of the data file. May be a standard file format name, or a description of organization of the data in a tabular file.',
  description STRING COMMENT 'The general description of this data link  MIAPPE V1.1 (DM-38) Data file description - Description of the format of the data file. May be a standard file format name, or a description of organization of the data in a tabular file.',
  fileFormat STRING COMMENT 'The MIME type of the file (ie text/csv, application/excel, application/zip).  MIAPPE V1.1 (DM-38) Data file description - Description of the format of the data file. May be a standard file format name, or a description of organization of the data in a tabular file.',
  name STRING COMMENT 'The name of the external data link  MIAPPE V1.1 (DM-38) Data file description - Description of the format of the data file. May be a standard file format name, or a description of organization of the data in a tabular file.',
  provenance STRING COMMENT 'The description of the origin or ownership of this linked data. Could be a formal reference to software, method, or workflow.',
  scientificType STRING COMMENT 'The general type of data. For example- Genotyping, Phenotyping raw data, Phenotyping reduced data, Environmental, etc',
  url STRING COMMENT 'URL describing the location of this data file to view or download  MIAPPE V1.1 (DM-37) Data file link - Link to the data file (or digital object) in a public database or in a persistent institutional repository; or identifier of the data file when submitted together with the MIAPPE submission.',
  version STRING COMMENT 'The version number for this data   MIAPPE V1.1 (DM-39) Data file version - The version of the dataset (the actual data).' > > COMMENT 'List of links to extra data files associated with this study. Extra data could include notes, images, and reference data.',
  documentationURL STRING COMMENT 'A URL to the human readable documentation of an object',
  endDate STRING COMMENT 'The date the study ends  MIAPPE V1.1 (DM-15) End date of study - Date and, if relevant, time when the experiment ended',
  environmentParameters ARRAY < STRUCT < description STRING COMMENT 'Human-readable value of the environment parameter (defined above) constant within the experiment',
  environmentParametersDbId STRING COMMENT 'Human-readable value of the environment parameter (defined above) constant within the experiment',
  parameterName STRING COMMENT 'Name of the environment parameter constant within the experiment  MIAPPE V1.1 (DM-58) Environment parameter - Name of the environment parameter constant within the experiment. ',
  parameterPUI STRING COMMENT 'URI pointing to an ontology class for the parameter',
  unit STRING COMMENT 'Unit of the value for this parameter',
  unitPUI STRING COMMENT 'URI pointing to an ontology class for the unit',
  value STRING COMMENT 'Numerical or categorical value  MIAPPE V1.1 (DM-59) Environment parameter value - Value of the environment parameter (defined above) constant within the experiment.',
  valuePUI STRING COMMENT 'URI pointing to an ontology class for the parameter value' > > COMMENT 'Environmental parameters that were kept constant throughout the study and did not change between observation units.  MIAPPE V1.1 (DM-57) Environment - Environmental parameters that were kept constant throughout the study and did not change between observation units or assays. Environment characteristics that vary over time, i.e. environmental variables, should be recorded as Observed Variables (see below).',
  experimentalDesign STRUCT < PUI STRING COMMENT 'MIAPPE V1.1 (DM-23) Type of experimental design - Type of experimental  design of the study, in the form of an accession number from the Crop Ontology.',
  description STRING COMMENT 'MIAPPE V1.1 (DM-22) Description of the experimental design - Short description of the experimental design, possibly including statistical design. In specific cases, e.g. legacy datasets or data computed from several studies, the experimental design can be "unknown"/"NA", "aggregated/reduced data", or simply ''none''.' > COMMENT 'The experimental and statistical design full description plus a category PUI taken from crop research ontology or agronomy ontology',
  externalReferences ARRAY < STRUCT < referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
  referenceSource STRING COMMENT 'An identifier for the source system or database of this reference' > > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  growthFacility STRUCT < PUI STRING COMMENT 'MIAPPE V1.1 (DM-27) Type of growth facility - Type of growth facility in which the study was carried out, in the form of an accession number from the Crop Ontology.',
  description STRING COMMENT 'MIAPPE V1.1 (DM-26) Description of growth facility - Short description of the facility in which the study was carried out.' > COMMENT 'Short description of the facility in which the study was carried out.',
  lastUpdate STRUCT < lastUpdateDbId STRING COMMENT 'The date and time when this study was last modified',
  timestamp STRING COMMENT 'The timestamp of the update.',
  version STRING COMMENT 'The version of the update.' > COMMENT 'The date and time when this study was last modified',
  license STRING COMMENT 'The usage license associated with the study data',
  locationDbId STRING COMMENT 'The unique identifier for a Location',
  locationName STRING COMMENT 'A human readable name for a Location <br/> MIAPPE V1.1 (DM-18) Experimental site name - The name of the natural site, experimental field, greenhouse, phenotyping facility, etc. where the experiment took place.',
  observationLevels ARRAY < STRUCT < levelName STRING COMMENT 'A name for this level   **Standard Level Names: study, field, entry, rep, block, sub-block, plot, sub-plot, plant, pot, sample**   For more information on Observation Levels, please review the <a target="_blank" href="https://wiki.brapi.org/index.php/Observation_Levels">Observation Levels documentation</a>. ',
  levelOrder INT COMMENT '`levelOrder` defines where that level exists in the hierarchy of levels. `levelOrder`''s lower numbers  are at the top of the hierarchy (ie field -> 1) and higher numbers are at the bottom of the hierarchy (ie plant -> 9).   For more information on Observation Levels, please review the <a target="_blank" href="https://wiki.brapi.org/index.php/Observation_Levels">Observation Levels documentation</a>. ' > > COMMENT 'Observation levels indicate the granularity level at which the measurements are taken. `levelName`  defines the level, `levelOrder` defines where that level exists in the hierarchy of levels.  `levelOrder`s lower numbers are at the top of the hierarchy (ie field > 0) and higher numbers are  at the bottom of the hierarchy (ie plant > 6).   **Standard Level Names: study, field, entry, rep, block, sub-block, plot, sub-plot, plant, pot, sample**   For more information on Observation Levels, please review the <a target="_blank" href="https://wiki.brapi.org/index.php/Observation_Levels">Observation Levels documentation</a>. ',
  observationUnitsDescription STRING COMMENT 'MIAPPE V1.1 (DM-25) Observation unit description - General description of the observation units in the study.',
  -- For property 'observationVariables' Link table 'ObservationVariableByStudy' will be created separately,
  seasons ARRAY < STRING > COMMENT 'List of seasons over which this study was performed.',
  startDate STRING COMMENT 'The date this study started  MIAPPE V1.1 (DM-14) Start date of study - Date and, if relevant, time when the experiment started',
  studyCode STRING COMMENT 'A short human readable code for a study',
  studyDbId STRING COMMENT 'The ID which uniquely identifies a study within the given database server  MIAPPE V1.1 (DM-11) Study unique ID - Unique identifier comprising the name or identifier for the institution/database hosting the submission of the study data, and the identifier of the study in that institution.',
  studyDescription STRING COMMENT 'The description of this study  MIAPPE V1.1 (DM-13) Study description - Human-readable text describing the study',
  studyName STRING COMMENT 'The human readable name for a study  MIAPPE V1.1 (DM-12) Study title - Human-readable text summarising the study',
  studyPUI STRING COMMENT 'A permanent unique identifier associated with this study data. For example, a URI or DOI',
  studyType STRING COMMENT 'The type of study being performed. ex. "Yield Trial", etc',
  trialDbId STRING COMMENT 'The ID which uniquely identifies a trial  MIAPPE V1.1 (DM-2) Investigation unique ID - Identifier comprising the unique name of the institution/database hosting the submission of the investigation data, and the accession number of the investigation in that institution.',
  trialName STRING COMMENT 'The human readable name of a trial  MIAPPE V1.1 (DM-3) Investigation title - Human-readable string summarising the investigation.',
  trialPUI STRING COMMENT 'A permanent identifier for a trial. Could be DOI or other URI formatted identifier.'
) CLUSTER BY (
  studyDbId,
  studyName,
  studyPUI,
  locationDbId,
  locationName,
  trialDbId,
  trialName,
  trialPUI
) COMMENT 'A Study represents an experiment that has taken place at a single location. The Study contains metadata about the parameters and design of the experiment. It can also be used to group results and data sets generated from the experiment. A Trial can represent a collection of one or more Studies.';
CREATE TABLE brapi_ContactByStudy (
  contactDbId STRING COMMENT 'The ID which uniquely identifies this contact  MIAPPE V1.1 (DM-33) Person ID - An identifier for the data submitter. If that submitter is an individual, ORCID identifiers are recommended.',
  studyDbId STRING COMMENT 'The ID which uniquely identifies a study within the given database server  MIAPPE V1.1 (DM-11) Study unique ID - Unique identifier comprising the name or identifier for the institution/database hosting the submission of the study data, and the identifier of the study in that institution.',
  studyName STRING COMMENT 'The human readable name for a study  MIAPPE V1.1 (DM-12) Study title - Human-readable text summarising the study',
  studyPUI STRING COMMENT 'A permanent unique identifier associated with this study data. For example, a URI or DOI'
) CLUSTER BY (contactDbId, studyDbId, studyName, studyPUI) COMMENT 'Link table for Study to Contact on property contacts';
CREATE TABLE brapi_ObservationVariableByStudy (
  observationVariableDbId STRING COMMENT 'Variable unique identifier  MIAPPE V1.1 (DM-83) Variable ID - Code used to identify the variable in the data file. We recommend using a variable definition from the Crop Ontology where possible. Otherwise, the Crop Ontology naming convention is recommended: <trait abbreviation>_<method abbreviation>_<scale abbreviation>). A variable ID must be unique within a given investigation.',
  observationVariableName STRING COMMENT 'Variable name (usually a short name)  MIAPPE V1.1 (DM-84) Variable name - Name of the variable.',
  observationVariablePUI STRING COMMENT 'The Permanent Unique Identifier of a Observation Variable, usually in the form of a URI',
  studyDbId STRING COMMENT 'The ID which uniquely identifies a study within the given database server  MIAPPE V1.1 (DM-11) Study unique ID - Unique identifier comprising the name or identifier for the institution/database hosting the submission of the study data, and the identifier of the study in that institution.',
  studyName STRING COMMENT 'The human readable name for a study  MIAPPE V1.1 (DM-12) Study title - Human-readable text summarising the study',
  studyPUI STRING COMMENT 'A permanent unique identifier associated with this study data. For example, a URI or DOI'
) CLUSTER BY (
  observationVariableDbId,
  observationVariableName,
  observationVariablePUI,
  studyDbId,
  studyName,
  studyPUI
) COMMENT 'Link table for Study to ObservationVariable on property observationVariables';