ALTER TABLE brapi_CallSets ADD CONSTRAINT CallSets_Samples_fk FOREIGN KEY(sampleDbId, samplePUI, sampleName) REFERENCES brapi_Samples ;
ALTER TABLE brapi_CallSets ADD CONSTRAINT CallSets_Studies_fk FOREIGN KEY(studyDbId, studyPUI, studyName) REFERENCES brapi_Studies ;
ALTER TABLE brapi_Calls ADD CONSTRAINT Calls_CallSets_fk FOREIGN KEY(callSetDbId, callSetName) REFERENCES brapi_CallSets ;
ALTER TABLE brapi_Calls ADD CONSTRAINT Calls_VariantSets_fk FOREIGN KEY(variantSetDbId, variantSetName) REFERENCES brapi_VariantSets ;
ALTER TABLE brapi_Calls ADD CONSTRAINT Calls_Variants_fk FOREIGN KEY(variantDbId) REFERENCES brapi_Variants ;
ALTER TABLE brapi_Crosses ADD CONSTRAINT Crosses_CrossingProjects_fk FOREIGN KEY(crossingProjectDbId, crossingProjectName) REFERENCES brapi_CrossingProjects ;
ALTER TABLE brapi_Crosses ADD CONSTRAINT Crosses_PlannedCrosses_fk FOREIGN KEY(plannedCrossDbId, plannedCrossName) REFERENCES brapi_PlannedCrosses ;
ALTER TABLE brapi_CrossingProjects ADD CONSTRAINT CrossingProjects_Programs_fk FOREIGN KEY(programDbId, programName) REFERENCES brapi_Programs ;
ALTER TABLE brapi_Events ADD CONSTRAINT Events_Studies_fk FOREIGN KEY(studyDbId, studyPUI, studyName) REFERENCES brapi_Studies ;
ALTER TABLE brapi_Germplasm ADD CONSTRAINT Germplasm_BreedingMethods_fk FOREIGN KEY(breedingMethodDbId, breedingMethodName) REFERENCES brapi_BreedingMethods ;
ALTER TABLE brapi_GermplasmAttributeValues ADD CONSTRAINT GermplasmAttributeValues_GermplasmAttributes_fk FOREIGN KEY(attributeDbId, attributePUI, attributeName) REFERENCES brapi_GermplasmAttributes ;
ALTER TABLE brapi_GermplasmAttributeValues ADD CONSTRAINT GermplasmAttributeValues_Germplasm_fk FOREIGN KEY(germplasmDbId, germplasmPUI, germplasmName) REFERENCES brapi_Germplasm ;
ALTER TABLE brapi_GermplasmAttributes ADD CONSTRAINT GermplasmAttributes_Methods_fk FOREIGN KEY(methodDbId, methodPUI, methodName) REFERENCES brapi_Methods ;
ALTER TABLE brapi_GermplasmAttributes ADD CONSTRAINT GermplasmAttributes_Scales_fk FOREIGN KEY(scaleDbId, scalePUI, scaleName) REFERENCES brapi_Scales ;
ALTER TABLE brapi_GermplasmAttributes ADD CONSTRAINT GermplasmAttributes_Traits_fk FOREIGN KEY(traitDbId, traitPUI, traitName) REFERENCES brapi_Traits ;
ALTER TABLE brapi_Images ADD CONSTRAINT Images_ObservationUnits_fk FOREIGN KEY(observationUnitDbId, observationUnitPUI, observationUnitName) REFERENCES brapi_ObservationUnits ;
ALTER TABLE brapi_Lists ADD CONSTRAINT Lists_People_fk FOREIGN KEY(listOwnerPersonDbId) REFERENCES brapi_People ;
ALTER TABLE brapi_Locations ADD CONSTRAINT Locations_Locations_fk FOREIGN KEY(parentLocationDbId, parentLocationName) REFERENCES brapi_Locations ;
ALTER TABLE brapi_ObservationUnits ADD CONSTRAINT ObservationUnits_Crosses_fk FOREIGN KEY(crossDbId, crossName) REFERENCES brapi_Crosses ;
ALTER TABLE brapi_ObservationUnits ADD CONSTRAINT ObservationUnits_Germplasm_fk FOREIGN KEY(germplasmDbId, germplasmPUI, germplasmName) REFERENCES brapi_Germplasm ;
ALTER TABLE brapi_ObservationUnits ADD CONSTRAINT ObservationUnits_Locations_fk FOREIGN KEY(locationDbId, locationName) REFERENCES brapi_Locations ;
ALTER TABLE brapi_ObservationUnits ADD CONSTRAINT ObservationUnits_Programs_fk FOREIGN KEY(programDbId, programName) REFERENCES brapi_Programs ;
ALTER TABLE brapi_ObservationUnits ADD CONSTRAINT ObservationUnits_SeedLots_fk FOREIGN KEY(seedLotDbId, seedLotName) REFERENCES brapi_SeedLots ;
ALTER TABLE brapi_ObservationUnits ADD CONSTRAINT ObservationUnits_Studies_fk FOREIGN KEY(studyDbId, studyPUI, studyName) REFERENCES brapi_Studies ;
ALTER TABLE brapi_ObservationUnits ADD CONSTRAINT ObservationUnits_Trials_fk FOREIGN KEY(trialDbId, trialPUI, trialName) REFERENCES brapi_Trials ;
ALTER TABLE brapi_ObservationVariables ADD CONSTRAINT ObservationVariables_Methods_fk FOREIGN KEY(methodDbId, methodPUI, methodName) REFERENCES brapi_Methods ;
ALTER TABLE brapi_ObservationVariables ADD CONSTRAINT ObservationVariables_Scales_fk FOREIGN KEY(scaleDbId, scalePUI, scaleName) REFERENCES brapi_Scales ;
ALTER TABLE brapi_ObservationVariables ADD CONSTRAINT ObservationVariables_Traits_fk FOREIGN KEY(traitDbId, traitPUI, traitName) REFERENCES brapi_Traits ;
ALTER TABLE brapi_Observations ADD CONSTRAINT Observations_Germplasm_fk FOREIGN KEY(germplasmDbId, germplasmPUI, germplasmName) REFERENCES brapi_Germplasm ;
ALTER TABLE brapi_Observations ADD CONSTRAINT Observations_ObservationUnits_fk FOREIGN KEY(observationUnitDbId, observationUnitPUI, observationUnitName) REFERENCES brapi_ObservationUnits ;
ALTER TABLE brapi_Observations ADD CONSTRAINT Observations_ObservationVariables_fk FOREIGN KEY(observationVariableDbId, observationVariablePUI, observationVariableName) REFERENCES brapi_ObservationVariables ;
ALTER TABLE brapi_Observations ADD CONSTRAINT Observations_Seasons_fk FOREIGN KEY(seasonDbId, seasonName) REFERENCES brapi_Seasons ;
ALTER TABLE brapi_Observations ADD CONSTRAINT Observations_Studies_fk FOREIGN KEY(studyDbId, studyPUI, studyName) REFERENCES brapi_Studies ;
ALTER TABLE brapi_PedigreeNodes ADD CONSTRAINT PedigreeNodes_BreedingMethods_fk FOREIGN KEY(breedingMethodDbId, breedingMethodName) REFERENCES brapi_BreedingMethods ;
ALTER TABLE brapi_PedigreeNodes ADD CONSTRAINT PedigreeNodes_CrossingProjects_fk FOREIGN KEY(crossingProjectDbId, crossingProjectName) REFERENCES brapi_CrossingProjects ;
ALTER TABLE brapi_PedigreeNodes ADD CONSTRAINT PedigreeNodes_Germplasm_fk FOREIGN KEY(germplasmDbId, germplasmPUI, germplasmName) REFERENCES brapi_Germplasm ;
ALTER TABLE brapi_PlannedCrosses ADD CONSTRAINT PlannedCrosses_CrossingProjects_fk FOREIGN KEY(crossingProjectDbId, crossingProjectName) REFERENCES brapi_CrossingProjects ;
ALTER TABLE brapi_Plates ADD CONSTRAINT Plates_Programs_fk FOREIGN KEY(programDbId, programName) REFERENCES brapi_Programs ;
ALTER TABLE brapi_Plates ADD CONSTRAINT Plates_Studies_fk FOREIGN KEY(studyDbId, studyPUI, studyName) REFERENCES brapi_Studies ;
ALTER TABLE brapi_Plates ADD CONSTRAINT Plates_Trials_fk FOREIGN KEY(trialDbId, trialPUI, trialName) REFERENCES brapi_Trials ;
ALTER TABLE brapi_Programs ADD CONSTRAINT Programs_People_fk FOREIGN KEY(leadPersonDbId) REFERENCES brapi_People ;
ALTER TABLE brapi_ReferenceSets ADD CONSTRAINT ReferenceSets_References_fk FOREIGN KEY(referencesDbId, referencesName) REFERENCES brapi_References ;
ALTER TABLE brapi_References ADD CONSTRAINT References_ReferenceSets_fk FOREIGN KEY(referenceSetDbId, referenceSetName) REFERENCES brapi_ReferenceSets ;
ALTER TABLE brapi_Samples ADD CONSTRAINT Samples_Germplasm_fk FOREIGN KEY(germplasmDbId, germplasmPUI, germplasmName) REFERENCES brapi_Germplasm ;
ALTER TABLE brapi_Samples ADD CONSTRAINT Samples_ObservationUnits_fk FOREIGN KEY(observationUnitDbId, observationUnitPUI, observationUnitName) REFERENCES brapi_ObservationUnits ;
ALTER TABLE brapi_Samples ADD CONSTRAINT Samples_Plates_fk FOREIGN KEY(plateDbId, plateName) REFERENCES brapi_Plates ;
ALTER TABLE brapi_Samples ADD CONSTRAINT Samples_Programs_fk FOREIGN KEY(programDbId, programName) REFERENCES brapi_Programs ;
ALTER TABLE brapi_Samples ADD CONSTRAINT Samples_Studies_fk FOREIGN KEY(studyDbId, studyPUI, studyName) REFERENCES brapi_Studies ;
ALTER TABLE brapi_Samples ADD CONSTRAINT Samples_Trials_fk FOREIGN KEY(trialDbId, trialPUI, trialName) REFERENCES brapi_Trials ;
ALTER TABLE brapi_SeedLots ADD CONSTRAINT SeedLots_Locations_fk FOREIGN KEY(locationDbId, locationName) REFERENCES brapi_Locations ;
ALTER TABLE brapi_SeedLots ADD CONSTRAINT SeedLots_Programs_fk FOREIGN KEY(programDbId, programName) REFERENCES brapi_Programs ;
ALTER TABLE brapi_Studies ADD CONSTRAINT Studies_Locations_fk FOREIGN KEY(locationDbId, locationName) REFERENCES brapi_Locations ;
ALTER TABLE brapi_Studies ADD CONSTRAINT Studies_Trials_fk FOREIGN KEY(trialDbId, trialPUI, trialName) REFERENCES brapi_Trials ;
ALTER TABLE brapi_Trials ADD CONSTRAINT Trials_Programs_fk FOREIGN KEY(programDbId, programName) REFERENCES brapi_Programs ;
ALTER TABLE brapi_VariantSets ADD CONSTRAINT VariantSets_ReferenceSets_fk FOREIGN KEY(referenceSetDbId, referenceSetName) REFERENCES brapi_ReferenceSets ;
ALTER TABLE brapi_VariantSets ADD CONSTRAINT VariantSets_Studies_fk FOREIGN KEY(studyDbId, studyPUI, studyName) REFERENCES brapi_Studies ;
ALTER TABLE brapi_Variants ADD CONSTRAINT Variants_ReferenceSets_fk FOREIGN KEY(referenceSetDbId, referenceSetName) REFERENCES brapi_ReferenceSets ;
ALTER TABLE brapi_Variants ADD CONSTRAINT Variants_References_fk FOREIGN KEY(referenceDbId, referenceName) REFERENCES brapi_References ;
ALTER TABLE brapi_Variants ADD CONSTRAINT Variants_VariantSets_fk FOREIGN KEY(variantSetDbId, variantSetName) REFERENCES brapi_VariantSets ;


-- Generated by Schema Tools Generator Version: '0.60.0'
