-- CallSet

/* 
A CallSet is a collection of Calls that were generated by the same analysis of the same Sample
 */
CREATE TABLE brapi_CallSets (
  callSetDbId STRING NOT NULL PRIMARY KEY COMMENT 'The ID which uniquely identifies a CallSet within the given database server',
  callSetName STRING PRIMARY KEY COMMENT 'The human readable name which identifies a germplasm within the given database server',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  created STRING COMMENT 'The date this call set was created',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  sampleDbId STRING COMMENT 'The ID which uniquely identifies a `Sample` <br> MIAPPE V1.1 (DM-76) Sample ID - Unique identifier for the sample.',
  samplePUI STRING COMMENT 'A permanent unique identifier for the `Sample` (DOI, URL, UUID, etc) <br> MIAPPE V1.1 (DM-81) External ID - An identifier for the sample in a persistent repository, comprising the name of the repository and the accession number of the observation unit therein. Submission to the EBI Biosamples repository is recommended. URI are recommended when possible. ',
  sampleName STRING NOT NULL COMMENT 'The human readable name of the `Sample`',
  studyDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies a study within the given database server  MIAPPE V1.1 (DM-11) Study unique ID - Unique identifier comprising the name or identifier for the institution/database hosting the submission of the study data, and the identifier of the study in that institution.',
  studyPUI STRING COMMENT 'A permanent unique identifier associated with this study data. For example, a URI or DOI',
  studyName STRING NOT NULL COMMENT 'The human readable name for a study  MIAPPE V1.1 (DM-12) Study title - Human-readable text summarising the study',
  updated STRING COMMENT 'The time at which this call set was last updated',
  -- For property 'variantSets' Link table 'VariantSetByCallSet' will be created separately
) 
COMMENT 'A CallSet is a collection of Calls that were generated by the same analysis of the same Sample';


/* 
Creates a lookup table for property 'variantSets' for 'CallSet' to 'VariantSet'
 */
CREATE TABLE brapi_VariantSetByCallSet (
  variantSetDbId STRING NOT NULL COMMENT 'The unique identifier for a VariantSet',
  variantSetName STRING COMMENT 'The human readable name for a VariantSet',
  callSetDbId STRING NOT NULL PRIMARY KEY COMMENT 'The ID which uniquely identifies a CallSet within the given database server',
  callSetName STRING PRIMARY KEY COMMENT 'The human readable name which identifies a germplasm within the given database server'
) 
COMMENT 'Link table for CallSet to VariantSet on property variantSets';


-- Generated by Schema Tools Generator Version: '0.60.0'
