-- Crop

/* 
A **Crop** is a plant that is grown for an economic purpose (e.g. human consumption). Crop_AP Data Catalog

Each Crop has at least a CommonCropName and a CropCode.

### Phenome Implementation

In Phenome a crop is defined as a Research Group in the User Interface and is merged with information
from the BASF Plant of Interest Ontology.

### PRISM Implementation

In PRISM crops are defined in the Crop_entry table and are merged with information
from the BASF Plant of Interest Ontology.

> TODO Breeding Services check what is seen in PRISM interface 

###  Examples

| Source                  | commonCropName   | cropCode        | cropDbId                             | cropGroup |
|-------------------------|------------------|-----------------|--------------------------------------|-----------|
| Field Crops             | Oilseed          | BRS             | e36bf51a-239b-3b5d-b245-df549845b084 | FC        |
| Vegetable Crops - PRISM | Artichoke        | AR              | 95c05b77-af34-3c95-b3a6-72c046a6ec47 | VC        |
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_crops (
  cropDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies a crop within the given database server',
  cropPUI STRING NOT NULL PRIMARY KEY COMMENT 'A permanent unique identifier associated with this Crop. For example, a URI or DOI',
  commonCropName STRING NOT NULL COMMENT 'Common name for the crop   MCPD (v2.1) (CROPNAME) 10. Common name of the crop. Example: "malting barley", "mas".',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  cropCode STRING NOT NULL COMMENT 'The most widely used 2-letter or 3-letter code for the crop. 2-letter codes are usually based on the common name, for example WH is the 2-letter for wheat.  3-letter codes are usually based on the genus and species, for example TRI is the 3-letter for wheat. To get explicitly the 2-letter or 3-letter crop code, look at the external references with reference source CROP_2_LETTER_CODE or CROP_3_LETTER_CODE, respectively.',
  cropGroup STRING NOT NULL COMMENT 'cropGroup: Crop',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  subCropPUIs ARRAY<STRING> NOT NULL COMMENT 'The list sub crops for this crop.',
  taxonIds
    ARRAY<
      STRUCT<
        sourceName STRING NOT NULL COMMENT 'The human readable name of the taxonomy provider',
        taxonId STRING NOT NULL COMMENT 'The identifier (name, ID, URI) of a particular taxonomy within the source provider'
      >
    > NOT NULL COMMENT 'The list of IDs for this SPECIES from different sources. If present, NCBI Taxon should be always listed as "ncbiTaxon" preferably with a purl. The rank of this ID should be species.  MIAPPE V1.1 (DM-42) Organism - An identifier for the organism at the species level. Use of the NCBI taxon ID is recommended.'
) 
USING delta
CLUSTER BY (commonCropName,cropCode)
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'A **Crop** is a plant that is grown for an economic purpose (e.g. human consumption). Crop_AP Data Catalog  Each Crop has at least a CommonCropName and a CropCode.  ### Phenome Implementation  In Phenome a crop is defined as a Research Group in the User Interface and is merged with information from the BASF Plant of Interest Ontology.  ### PRISM Implementation  In PRISM crops are defined in the Crop_entry table and are merged with information from the BASF Plant of Interest Ontology.  > TODO Breeding Services check what is seen in PRISM interface   ###  Examples  | Source                  | commonCropName   | cropCode        | cropDbId                             | cropGroup | |-------------------------|------------------|-----------------|--------------------------------------|-----------| | Field Crops             | Oilseed          | BRS             | e36bf51a-239b-3b5d-b245-df549845b084 | FC        | | Vegetable Crops - PRISM | Artichoke        | AR              | 95c05b77-af34-3c95-b3a6-72c046a6ec47 | VC        |';


-- Generated by Schema Tools Generator Version: '0.60.0'
