-- CultivarAttributeValue

/* 
Cultivar "attributes" values are simply-inherited characteristics (characterization descriptors) that are not environment-dependent but 
inherent in the cultivar line.  They include genes, QTLs, and genetic "traits" like wheat grain 
hardness.  They are often evaluated by genotyping for diagnostic markers.
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_cultivar_attribute_values (
  attributeValueDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies this attribute value within the given database server',
  attributeValuePUI STRING PRIMARY KEY COMMENT 'The Permanent Unique Identifier of an Attribute Value, usually in the form of a URI',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  attributePUI STRING NOT NULL COMMENT 'The Permanent Unique Identifier of an Attribute, usually in the form of a URI',
  cultivarPUI STRING NOT NULL COMMENT 'The Permanent Unique Identifier which represents a cultivar',
  determinedDate STRING COMMENT 'The date the value of this attribute was determined for a given germplasm',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  value STRING COMMENT 'The value of this attribute for a given entity'
) 
USING delta
CLUSTER BY (determinedDate)
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'Cultivar "attributes" values are simply-inherited characteristics (characterization descriptors) that are not environment-dependent but  inherent in the cultivar line.  They include genes, QTLs, and genetic "traits" like wheat grain  hardness.  They are often evaluated by genotyping for diagnostic markers.';


-- Generated by Schema Tools Generator Version: '0.60.0'
