DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_attribute_categories ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_breeding_methods ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_crops ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_cultivar_attribute_values ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_cultivar_attributes ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_cultivars ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_germplasm ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_germplasm_attribute_values ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_germplasm_attributes ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_inventory_lot_attribute_values ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_inventory_lot_attributes ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_inventory_lot_sets ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_inventory_lots ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_locale_attribute_values ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_locale_attributes ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_locales ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_locations ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_observation_unit_attribute_values ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_observation_unit_attributes ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_observation_units ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_observation_variables ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_observations ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_pedigree_nodes ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_programs ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_scales ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_seasons ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_studies ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_study_types ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_trials ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_varieties ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_variety_attribute_values ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_variety_attributes ;
DROP TABLE IF EXISTS sta_dash.dadi_br_sandbox.silver_phenome_variety_stages ;


-- Generated by Schema Tools Generator Version: '0.60.0'
