-- GenomeMap

/* 
The GenomeMap represents the metadata associated with a reference map of a particular species genome. A GenomeMap can either represent a physical map or genetic map.
 */
CREATE TABLE brapi_GenomeMaps (
  mapDbId STRING PRIMARY KEY COMMENT 'The unique identifier for a `GenomeMap`',
  mapName STRING PRIMARY KEY COMMENT 'The human readable identifier for a `GenomeMap`',
  mapPUI STRING PRIMARY KEY COMMENT 'The DOI or other permanent identifier for a `GenomeMap`',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  comments STRING COMMENT 'Additional comments about a `GenomeMap`',
  commonCropName STRING NOT NULL COMMENT 'The common name of the `Crop`',
  documentationURL STRING COMMENT 'A URL to the human readable documentation of an object',
  linkageGroupCount INT COMMENT 'The number of linkage groups present in a `GenomeMap`',
  linkageGroups
    ARRAY<
      STRUCT<
        linkageGroupName STRING COMMENT 'The Uniquely Identifiable name of a `LinkageGroup` <br> This might be a chromosome identifier or the generic linkage group identifier if the chromosome is not applicable.',
        additionalInfo MAP<STRING,STRING> COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
        genomeMapDbId STRING COMMENT 'The unique identifier for a `GenomeMap`',
        genomeMapPUI STRING COMMENT 'The DOI or other permanent identifier for a `GenomeMap`',
        genomeMapName STRING COMMENT 'The human readable identifier for a `GenomeMap`',
        markerCount INT COMMENT 'The number of markers associated with a `LinkageGroup`.',
        maxPosition INT COMMENT 'The maximum position of a marker within a `LinkageGroup`.'
      >
    > COMMENT 'The linkage groups present in a `GenomeMap`',
  markerCount INT COMMENT 'The number of markers present in a `GenomeMap`',
  publishedDate STRING COMMENT 'The date this `GenomeMap` was published',
  scientificName STRING COMMENT 'Full scientific binomial format name. This includes Genus, Species, and Sub-species',
  type STRING NOT NULL COMMENT 'The type of map this represents, usually "Genetic" or "Physical"',
  unit STRING COMMENT 'The units used to describe the data in a `GenomeMap`'
) 
COMMENT 'The GenomeMap represents the metadata associated with a reference map of a particular species genome. A GenomeMap can either represent a physical map or genetic map.';


-- Generated by Schema Tools Generator Version: '0.60.0'
