-- GermplasmAttribute

/* 
The Trait-Method-Scale definition for a variable, specifically variables related to Germplasm. Similar to an ObservationVariable, but related to a Germplasm instead of an ObservationUnit
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_germplasm_attributes (
  attributeDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies this attribute within the given database server',
  attributeName STRING NOT NULL COMMENT 'A human readable name for this attribute',
  attributePUI STRING NOT NULL PRIMARY KEY COMMENT 'The Permanent Unique Identifier of an Attribute, usually in the form of a URI',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  attributeCategory STRING NOT NULL COMMENT 'General category for the attribute. very similar to Trait class.',
  attributeDescription STRING NOT NULL COMMENT 'A human readable description of this attribute',
  attributeType STRING NOT NULL COMMENT 'The type of this attribute, which can Attribute or Factor',
  attributeValuePUIs ARRAY<STRING> COMMENT 'attributeValues',
  commonCropName STRING COMMENT 'Crop name (examples: "Maize", "Wheat")',
  contextOfUse ARRAY<STRING> COMMENT 'Indication of how trait is routinely used. (examples: ["Trial evaluation", "Nursery evaluation"])',
  defaultValue STRING COMMENT 'Variable default value. (examples: "red", "2.3", etc.)',
  documentationURL STRING COMMENT 'A URL to the human readable documentation of an object',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  growthStage STRING COMMENT 'Growth stage at which measurement is made (examples: "flowering")',
  institution STRING COMMENT 'Name of institution submitting the variable',
  language STRING COMMENT '2 letter ISO 639-1 code for the language of submission of the variable.',
  methodPUI STRING COMMENT 'The Permanent Unique Identifier of a Method, usually in the form of a URI',
  ontologyReference 
    STRUCT<
      ontologyReferenceDbId STRING COMMENT 'The ID which uniquely identifies a ontology reference',
      documentationLinks
        ARRAY<
          STRUCT<
            URL STRING COMMENT 'The URL or URI to the documentation',
            type STRING COMMENT 'The type of documentation, which can be OBO Foundry, an RDF term or a webpage.'
          >
        > COMMENT 'links to various ontology documentation',
      ontologyDbId STRING NOT NULL COMMENT 'Ontology database unique identifier',
      version STRING COMMENT 'Ontology version (no specific format)'
    > NOT NULL COMMENT 'MIAPPE V1.1  (DM-85) Variable accession number - Accession number of the variable in the Crop Ontology  (DM-87) Trait accession number - Accession number of the trait in a suitable controlled vocabulary (Crop Ontology, Trait Ontology).  (DM-89) Method accession number - Accession number of the method in a suitable controlled vocabulary (Crop Ontology, Trait Ontology).  (DM-93) Scale accession number - Accession number of the scale in a suitable controlled vocabulary (Crop Ontology).',
  scalePUI STRING COMMENT 'The Permanent Unique Identifier of a Scale, usually in the form of a URI',
  scientist STRING COMMENT 'Name of scientist submitting the variable.',
  status STRING COMMENT 'Variable status. (examples: "recommended", "obsolete", "legacy", etc.)',
  submissionTimestamp STRING COMMENT 'Timestamp when the Variable was added (ISO 8601)',
  synonyms ARRAY<STRING> COMMENT 'Other variable names',
  traitPUI STRING COMMENT 'The Permanent Unique Identifier of a Trait, usually in the form of a URI'
) 
USING delta
CLUSTER BY (commonCropName)
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'The Trait-Method-Scale definition for a variable, specifically variables related to Germplasm. Similar to an ObservationVariable, but related to a Germplasm instead of an ObservationUnit';


/* 
Controlled Vocabulary for attributeCategories of GermplasmAttribute
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_attribute_categories (
  attributeCategory STRING NOT NULL COMMENT 'General category for the attribute. very similar to Trait class.'
) 
USING delta
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'Controlled Vocabulary table for property attributeCategory on GermplasmAttribute';


-- Generated by Schema Tools Generator Version: '0.60.0'
