-- Image

/* 
The metadata for an image file that is connected to some phenotypic observation data.
 */
CREATE TABLE brapi_Images (
  imageDbId STRING NOT NULL PRIMARY KEY COMMENT 'The unique identifier of an image',
  imageName STRING PRIMARY KEY COMMENT 'The human readable name of an image. Might be the same as ''imageFileName'', but could be different.',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  copyright STRING COMMENT 'The copyright information of this image. Example ''Copyright 2018 Bob Robertson''',
  description STRING COMMENT 'The human readable description of an image.',
  descriptiveOntologyTerms ARRAY<STRING> COMMENT 'A list of terms to formally describe the image. Each item could be a simple Tag, an Ontology reference Id, or a full ontology URL.',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  imageContent STRING NOT NULL COMMENT 'The content of the image',
  imageFileName STRING COMMENT 'The name of the image file. Might be the same as ''imageName'', but could be different.',
  imageFileSize INT COMMENT 'The size of the image in Bytes.',
  imageHeight INT COMMENT 'The height of the image in Pixels.',
  imageLocation 
    STRUCT<
      geometry1
        STRUCT<
          coordinates ARRAY<DOUBLE> COMMENT 'A single position',
          type STRING COMMENT 'The literal string "Point"'
        >,
      geometry2
        STRUCT<
          coordinates ARRAY<DOUBLE> COMMENT 'An array of linear rings',
          type STRING COMMENT 'The literal string "Polygon"'
        > COMMENT 'A geometry as defined by GeoJSON (RFC 7946). In this context, only Point or Polygon geometry are allowed.',
      type STRING COMMENT 'The literal string "Feature"'
    > NOT NULL COMMENT 'One geometry as defined by GeoJSON (RFC 7946). All coordinates are decimal values on the WGS84 geographic coordinate reference system.  Copied from RFC 7946 Section 3.1.1  A position is an array of numbers. There MUST be two or more elements. The first two elements are longitude and latitude, or easting and northing, precisely in that order and using decimal numbers. Altitude or elevation MAY be included as an optional third element.',
  imageTimeStamp STRING COMMENT 'The date and time the image was taken',
  imageURL STRING COMMENT 'The complete, absolute URI path to the image file. Images might be stored on a different host or path than the BrAPI web server.',
  imageWidth INT COMMENT 'The width of the image in Pixels.',
  mimeType STRING COMMENT 'The file type of the image. Examples ''image/jpeg'', ''image/png'', ''image/svg'', etc',
  observationUnitDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies an observation unit  MIAPPE V1.1 (DM-70) Observation unit ID - Identifier used to identify the observation unit in data files containing the values observed or measured on that unit. Must be locally unique. ',
  observationUnitPUI STRING COMMENT 'A Permanent Unique Identifier for an observation unit  MIAPPE V1.1 (DM-72) External ID - Identifier for the observation unit in a persistent repository, comprises the name of the repository and the identifier of the observation unit therein. The EBI Biosamples repository can be used. URI are recommended when possible.',
  observationUnitName STRING COMMENT 'A human readable name for an observation unit',
  -- For property 'observations' Link table 'ObservationByImage' will be created separately
) 
COMMENT 'The metadata for an image file that is connected to some phenotypic observation data.';


/* 
Creates a lookup table for property 'observations' for 'Image' to 'Observation'
 */
CREATE TABLE brapi_ObservationByImage (
  observationDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies an observation',
  imageDbId STRING NOT NULL PRIMARY KEY COMMENT 'The unique identifier of an image',
  imageName STRING PRIMARY KEY COMMENT 'The human readable name of an image. Might be the same as ''imageFileName'', but could be different.'
) 
COMMENT 'Link table for Image to Observation on property observations';


-- Generated by Schema Tools Generator Version: '0.60.0'
