-- InventoryLotAttributeValue

/* 
Inventory Lot Attribute Values are the value associated with
InventoryLots for a specific InventoryLotAttribute.

### Phenome Implementation
Inventory Lot Attribute Values are values for those variables
that have been assigned to the Inventory Lot entity.

### PRISM Implementation

In Field Crops and Vegetable Crops Cultivar Attributes Values are values
in specific columns in the Inventory table.
> TODO Breeding Services please check
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_inventory_lot_attribute_values (
  attributeValueDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies this attribute value within the given database server',
  attributeValuePUI STRING PRIMARY KEY COMMENT 'The Permanent Unique Identifier of an Attribute Value, usually in the form of a URI',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  attributePUI STRING NOT NULL COMMENT 'The Permanent Unique Identifier of an Attribute, usually in the form of a URI',
  determinedDate STRING COMMENT 'The date the value of this attribute was determined for a given germplasm',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  inventoryLotPUI STRING NOT NULL COMMENT 'A permanent unique identifier associated with this Seed Lot. For example, a URI or DOI',
  value STRING COMMENT 'The value of this attribute for a given entity'
) 
USING delta
CLUSTER BY (determinedDate)
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'Inventory Lot Attribute Values are the value associated with InventoryLots for a specific InventoryLotAttribute.  ### Phenome Implementation Inventory Lot Attribute Values are values for those variables that have been assigned to the Inventory Lot entity.  ### PRISM Implementation  In Field Crops and Vegetable Crops Cultivar Attributes Values are values in specific columns in the Inventory table. > TODO Breeding Services please check';


-- Generated by Schema Tools Generator Version: '0.60.0'
