-- InventoryLotSet

/* 
An **InventoryLotSet**  is a collection of InventoryLots brought together for a particular purpose.

### Phenome Implementation

> TODO Breeding Services what is the inventory lot concept in Phenome?

An InventoryLotSet in Phenome can be migrated from PRISM or newly created in Phenome.

### PRISM Implementation

InventoryLotSet is represented by an Inventory Book concept in PRISM.
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_inventory_lot_sets (
  inventoryLotSetDbId STRING NOT NULL COMMENT 'The unique identifier for an Inventory Lot Set',
  inventoryLotSetName STRING NOT NULL COMMENT 'Human readable name of a Inventory Lot Set',
  inventoryLotSetPUI STRING NOT NULL PRIMARY KEY COMMENT 'The Permanent Unique Identifier which represents a Inventory Lot Set',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'Additional arbitrary info',
  commonCropName STRING NOT NULL COMMENT 'Common name for the crop   MCPD (v2.1) (CROPNAME) 10. Common name of the crop. Example: "malting barley", "mas".',
  cropPUI STRING NOT NULL COMMENT 'A permanent unique identifier associated with this Crop. For example, a URI or DOI',
  dateCreated STRING NOT NULL COMMENT 'Timestamp when the Inventory Lot Set was first created',
  dateModified STRING NOT NULL COMMENT 'Timestamp when the Inventory Lot Set was last updated',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  inventoryLotSetDescription STRING NOT NULL COMMENT 'Description of an Inventory Lot Set',
  inventoryLotSetOwnerName STRING NOT NULL COMMENT 'Human readable name of an Inventory Lot Set Owner. (usually a user or person)',
  inventoryLotSetOwnerPersonDbId STRING NOT NULL COMMENT 'The unique identifier for an Inventory Lot Set Owner. (usually a user or person)',
  inventoryLotSetSize INT NOT NULL COMMENT 'The number of elements in an Inventory Lot Set',
  inventoryLotSetSource STRING NOT NULL COMMENT 'The description of where an Inventory Lot Set originated from',
  inventoryLotPUIs ARRAY<STRING> COMMENT 'The Inventory Lots (Seed Lots) within this set',
  programPUI STRING COMMENT 'A permanent identifier for a program. Could be DOI or other URI formatted identifier.'
) 
USING delta
CLUSTER BY (commonCropName)
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'An **InventoryLotSet**  is a collection of InventoryLots brought together for a particular purpose.  ### Phenome Implementation  > TODO Breeding Services what is the inventory lot concept in Phenome?  An InventoryLotSet in Phenome can be migrated from PRISM or newly created in Phenome.  ### PRISM Implementation  InventoryLotSet is represented by an Inventory Book concept in PRISM.';


-- Generated by Schema Tools Generator Version: '0.60.0'
