-- List

/* 
A List represents a collection of other BrAPI data objects. Typically these are custom lists generated by a user to keep track of interesting data. For example, a user might build a List of Germplasm that they have manually marked for further study.
 */
CREATE TABLE brapi_Lists (
  -- Primary properties
  listDbId STRING NOT NULL PRIMARY KEY COMMENT 'The unique identifier for a List',
  listName STRING NOT NULL PRIMARY KEY COMMENT 'Human readable name of a List',
  -- Link properties
  listOwnerPersonDbId STRING NOT NULL COMMENT 'Unique ID for a person',
  -- Properties
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  data ARRAY<STRING> COMMENT 'The array of DbIds of the BrAPI objects contained in a List',
  dateCreated STRING COMMENT 'Timestamp when the entity was first created',
  dateModified STRING COMMENT 'Timestamp when the entity was last updated',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  listDescription STRING COMMENT 'Description of a List',
  listOwnerName STRING COMMENT 'Human readable name of a List Owner. (usually a user or person)',
  listSize INT COMMENT 'The number of elements in a List',
  listSource STRING COMMENT 'The description of where a List originated from',
  listType STRING NOT NULL COMMENT 'A flag to indicate the type of objects that are referenced in a List'
) 
COMMENT 'A List represents a collection of other BrAPI data objects. Typically these are custom lists generated by a user to keep track of interesting data. For example, a user might build a List of Germplasm that they have manually marked for further study.';


-- Generated by Schema Tools Generator Version: '0.60.0'
