-- LocaleAttributeValue

/* 
Locale Attribute Values are the values of LocaleAttribute
associated with a specific Locale.

### Phenome Implementation
Locale Attribute Values are values for those variables
that have been assigned to the Locale entity.

### PRISM Implementation

In Field Crops and Vegetable Crops, Locale Attribute Values are values
for specific columns in the **field_notes** table.
> TODO Breeding Services please check
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_locale_attribute_values (
  attributeValueDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies this attribute value within the given database server',
  attributeValuePUI STRING PRIMARY KEY COMMENT 'The Permanent Unique Identifier of an Attribute Value, usually in the form of a URI',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  attributePUI STRING NOT NULL COMMENT 'The Permanent Unique Identifier of an Attribute, usually in the form of a URI',
  determinedDate STRING COMMENT 'The date the value of this attribute was determined for a given germplasm',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  localePUI STRING COMMENT 'A permanent unique identifier associated with this locale. For example, a URI or DOI',
  value STRING COMMENT 'The value of this attribute for a given entity'
) 
USING delta
CLUSTER BY (determinedDate)
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'Locale Attribute Values are the values of LocaleAttribute associated with a specific Locale.  ### Phenome Implementation Locale Attribute Values are values for those variables that have been assigned to the Locale entity.  ### PRISM Implementation  In Field Crops and Vegetable Crops, Locale Attribute Values are values for specific columns in the **field_notes** table. > TODO Breeding Services please check';


-- Generated by Schema Tools Generator Version: '0.60.0'
