-- Method

/* 
A description of the way an Observation should be collected. 
<br>For example, an ObservationVariable might be defined with a Trait of "plant height", a Scale of "meters", and a Method of "tape measure". This variable would be distinct from a variable with the Method "estimation" or "drone image processing". 
 */
CREATE TABLE brapi_Methods (
  -- Primary properties
  methodDbId STRING PRIMARY KEY COMMENT 'Method unique identifier',
  methodName STRING NOT NULL PRIMARY KEY COMMENT 'Human readable name for the method <br/>MIAPPE V1.1 (DM-88) Method  Name of the method of observation',
  methodPUI STRING PRIMARY KEY COMMENT 'The Permanent Unique Identifier of a Method, usually in the form of a URI',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  bibliographicalReference STRING COMMENT 'Bibliographical reference describing the method. <br/>MIAPPE V1.1 (DM-91) Reference associated to the method - URI/DOI of reference describing the method.',
  description STRING COMMENT 'Method description <br/>MIAPPE V1.1 (DM-90) Method description - Textual description of the method, which may extend a method defined in an external reference with specific parameters, e.g. growth stage, inoculation precise organ (leaf number)',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  formula STRING COMMENT 'For computational methods i.e., when the method consists in assessing the trait by computing measurements, write the generic formula used for the calculation',
  methodClass STRING COMMENT 'Method class (examples: "Measurement", "Counting", "Estimation", "Computation", etc.)',
  ontologyReference 
    STRUCT<
      -- Primary properties
      ontologyReferenceDbId STRING COMMENT 'The ID which uniquely identifies a ontology reference',
      -- Link properties
      ontologyDbId STRING COMMENT 'Ontology database unique identifier',
      ontologyName STRING COMMENT 'Ontology name',
      -- Properties
      documentationLinks
        ARRAY<
          STRUCT<
            URL STRING COMMENT 'The URL or URI to the documentation',
            type STRING COMMENT 'The type of documentation, which can be OBO Foundry, an RDF term or a webpage.'
          >
        > COMMENT 'links to various ontology documentation',
      version STRING COMMENT 'Ontology version (no specific format)'
    > NOT NULL COMMENT 'MIAPPE V1.1  (DM-85) Variable accession number - Accession number of the variable in the Crop Ontology  (DM-87) Trait accession number - Accession number of the trait in a suitable controlled vocabulary (Crop Ontology, Trait Ontology).  (DM-89) Method accession number - Accession number of the method in a suitable controlled vocabulary (Crop Ontology, Trait Ontology).  (DM-93) Scale accession number - Accession number of the scale in a suitable controlled vocabulary (Crop Ontology).'
) 
COMMENT 'A description of the way an Observation should be collected.  <br>For example, an ObservationVariable might be defined with a Trait of "plant height", a Scale of "meters", and a Method of "tape measure". This variable would be distinct from a variable with the Method "estimation" or "drone image processing". ';


-- Generated by Schema Tools Generator Version: '0.65.0'
