-- ObservationUnitAttributeValue

/* 
Observation Unit Attributes Values are values for Observation Unit Attribute
associated with an Observation Unit but are not Observations. Typically,
they are characteristics known before the start of the
trial or study. 

### Phenome Implementation

Observation Unit Attribute Values are values for Variables with the 
Variable type 'Variate'.

### PRISM Implementation

> TODO Breeding Services please check

In Field Crops and Vegetable Observation Variables are held different workbooks depending
on the type of study and are columns in the corresponding field book table.
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_observation_unit_attribute_values (
  attributeValueDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies this attribute value within the given database server',
  attributeValuePUI STRING PRIMARY KEY COMMENT 'The Permanent Unique Identifier of an Attribute Value, usually in the form of a URI',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  attributePUI STRING NOT NULL COMMENT 'The Permanent Unique Identifier of an Attribute, usually in the form of a URI',
  determinedDate STRING COMMENT 'The date the value of this attribute was determined for a given germplasm',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  observationUnitPUI STRING COMMENT 'A Permanent Unique Identifier for an observation unit  MIAPPE V1.1 (DM-72) External ID - Identifier for the observation unit in a persistent repository, comprises the name of the repository and the identifier of the observation unit therein. The EBI Biosamples repository can be used. URI are recommended when possible.',
  value STRING COMMENT 'The value of this attribute for a given entity'
) 
USING delta
CLUSTER BY (determinedDate)
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'Observation Unit Attributes Values are values for Observation Unit Attribute associated with an Observation Unit but are not Observations. Typically, they are characteristics known before the start of the trial or study.   ### Phenome Implementation  Observation Unit Attribute Values are values for Variables with the  Variable type \\'Variate\\'.  ### PRISM Implementation  > TODO Breeding Services please check  In Field Crops and Vegetable Observation Variables are held different workbooks depending on the type of study and are columns in the corresponding field book table.';


-- Generated by Schema Tools Generator Version: '0.60.0'
