-- Observation

/* 
A value assigned for a specific ObservationVariable when observing a specific ObservationUnit.
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_observations (
  observationDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies an observation',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  collector STRING COMMENT 'The name or identifier of the entity which collected the observation',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  geoCoordinates 
    STRUCT<
      geometry1
        STRUCT<
          coordinates ARRAY<DOUBLE> NOT NULL COMMENT 'A single position',
          type STRING NOT NULL COMMENT 'The literal string "Point"'
        >,
      geometry2
        STRUCT<
          coordinates ARRAY<DOUBLE> NOT NULL COMMENT 'An array of linear rings',
          type STRING NOT NULL COMMENT 'The literal string "Polygon"'
        > NOT NULL COMMENT 'A geometry as defined by GeoJSON (RFC 7946). In this context, only Point or Polygon geometry are allowed.',
      type STRING NOT NULL COMMENT 'The literal string "Feature"'
    > NOT NULL COMMENT 'One geometry as defined by GeoJSON (RFC 7946). All coordinates are decimal values on the WGS84 geographic coordinate reference system.  Copied from RFC 7946 Section 3.1.1  A position is an array of numbers. There MUST be two or more elements. The first two elements are longitude and latitude, or easting and northing, precisely in that order and using decimal numbers. Altitude or elevation MAY be included as an optional third element.',
  germplasmPUI STRING NOT NULL COMMENT 'The Permanent Unique Identifier which represents a germplasm  MIAPPE V1.1 (DM-41) Biological material ID - Code used to identify the biological material in the data file. Should be unique within the Investigation. Can correspond to experimental plant ID, inventory lot ID, etc This material identification is different from a BiosampleID which corresponds to Observation Unit or Samples sections below.  MIAPPE V1.1 (DM-51) Material source DOI - Digital Object Identifier (DOI) of the material source  MCPD (v2.1) (PUID) 0. Any persistent, unique identifier assigned to the accession so it can be unambiguously referenced at the global level and the information associated with it harvested through automated means. Report one PUID for each accession. The Secretariat of the International Treaty on Plant Genetic Resources for Food and Agriculture (PGRFA) is facilitating the assignment of a persistent unique identifier (PUID), in the form of a DOI, to PGRFA at the accession level. Genebanks not applying a true PUID to their accessions should use, and request recipients to use, the concatenation of INSTCODE, ACCENUMB, and GENUS as a globally unique identifier similar in most respects to the PUID whenever they exchange information on accessions with third parties.',
  observationTimeStamp STRING COMMENT 'The date and time when this observation was made',
  observationUnitPUI STRING COMMENT 'A Permanent Unique Identifier for an observation unit  MIAPPE V1.1 (DM-72) External ID - Identifier for the observation unit in a persistent repository, comprises the name of the repository and the identifier of the observation unit therein. The EBI Biosamples repository can be used. URI are recommended when possible.',
  observationVariablePUI STRING COMMENT 'The Permanent Unique Identifier of a Observation Variable, usually in the form of a URI',
  seasonPUI STRING COMMENT 'A permanent unique identifier associated with this season. For example, a URI or DOI.',
  studyPUI STRING COMMENT 'A permanent unique identifier associated with this study data. For example, a URI or DOI',
  uploadedBy STRING COMMENT 'The name or id of the user who uploaded the observation to the database system',
  value STRING COMMENT 'The value of the data collected as an observation'
) 
USING delta
CLUSTER BY (observationTimeStamp)
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'A value assigned for a specific ObservationVariable when observing a specific ObservationUnit.';


-- Generated by Schema Tools Generator Version: '0.60.0'
