-- Ontology

/* 
The identifier and metadata needed to reference an external controlled vocabulary
 */
CREATE TABLE brapi_Ontologies (
  ontologyDbId STRING NOT NULL PRIMARY KEY COMMENT 'Ontology database unique identifier',
  ontologyName STRING NOT NULL PRIMARY KEY COMMENT 'Ontology name',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  authors STRING COMMENT 'Ontology''s list of authors (no specific format)',
  copyright STRING COMMENT 'Ontology copyright',
  description STRING COMMENT 'Human readable description of Ontology',
  documentationURL STRING COMMENT 'A URL to the human readable documentation of an object',
  licence STRING COMMENT 'Ontology licence',
  version STRING COMMENT 'Ontology version (no specific format)'
) 
COMMENT 'The identifier and metadata needed to reference an external controlled vocabulary';


-- Generated by Schema Tools Generator Version: '0.60.0'
