-- Person

/* 
A generic object used to maintain the metadata needed to describe a human. The Person might be a software user, a field technician, or a primary contact for a Program.
 */
CREATE TABLE brapi_People (
  -- Primary properties
  personDbId STRING NOT NULL PRIMARY KEY COMMENT 'Unique ID for a person',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  description STRING COMMENT 'description of this person',
  emailAddress STRING COMMENT 'email address for this person',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  firstName STRING COMMENT 'Persons first name',
  lastName STRING COMMENT 'Persons last name',
  mailingAddress STRING COMMENT 'physical address of this person',
  middleName STRING COMMENT 'Persons middle name',
  phoneNumber STRING COMMENT 'phone number of this person',
  userID STRING COMMENT 'A systems user ID associated with this person. Different from personDbId because you could have a person who is not a user of the system.'
) 
COMMENT 'A generic object used to maintain the metadata needed to describe a human. The Person might be a software user, a field technician, or a primary contact for a Program.';


-- Generated by Schema Tools Generator Version: '0.60.0'
