-- Program

/* 
A BrAPI Program represents the high level organization or group who is responsible for conducting trials and studies. Things like Breeding Programs and Funded Projects are considered BrAPI Programs. A Program can contain multiple Trials. A Trial can contain multiple Studies.
 */
CREATE TABLE brapi_Programs (
  programDbId STRING NOT NULL PRIMARY KEY COMMENT 'The ID which uniquely identifies the program',
  programName STRING NOT NULL PRIMARY KEY COMMENT 'Human readable name of the program',
  abbreviation STRING COMMENT 'A shortened version of the human readable name for a Program',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  commonCropName STRING COMMENT 'Common name for the crop which this program is for',
  documentationURL STRING COMMENT 'A URL to the human readable documentation of an object',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  fundingInformation STRING COMMENT 'Information describing the grant or funding source for this program',
  leadPersonDbId STRING NOT NULL COMMENT 'Unique ID for a person',
  objective STRING COMMENT 'The primary objective of the program',
  programType STRING COMMENT 'The type of program entity this object represents <br/> ''STANDARD'' represents a standard, permanent breeding program <br/> ''PROJECT'' represents a short term project, usually with a set time limit based on funding   '
) 
COMMENT 'A BrAPI Program represents the high level organization or group who is responsible for conducting trials and studies. Things like Breeding Programs and Funded Projects are considered BrAPI Programs. A Program can contain multiple Trials. A Trial can contain multiple Studies.';


-- Generated by Schema Tools Generator Version: '0.60.0'
