-- Season

/* 
A Season defines a period in time. A Season is made of two parts; (1) the primary year and (2) a term which defines a segment of the year. This term could be a traditional season, like "Spring" or "Summer", or this term could be a month, like "May" or "June", or this could be an arbitrary season name which is meaningful to the breeding Program like "PlantingTime_3" or "Season E".
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_seasons (
  seasonDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies a season. For backward compatibility it can be a string like \'2012\', \'1957-2004\'',
  seasonName STRING COMMENT 'Name of the season. ex. \'Spring\', \'Q2\', \'Season A\', etc.',
  seasonPUI STRING PRIMARY KEY COMMENT 'A permanent unique identifier associated with this season. For example, a URI or DOI.',
  quarter INT NOT NULL COMMENT 'The 1 digit quarter of the season if the season represents a quarter year.',
  year INT COMMENT 'The 4 digit year of the season.'
) 
USING delta
CLUSTER BY (year,quarter)
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'A Season defines a period in time. A Season is made of two parts; (1) the primary year and (2) a term which defines a segment of the year. This term could be a traditional season, like "Spring" or "Summer", or this term could be a month, like "May" or "June", or this could be an arbitrary season name which is meaningful to the breeding Program like "PlantingTime_3" or "Season E".';


-- Generated by Schema Tools Generator Version: '0.60.0'
