-- Season

/* 
A Season defines a period in time. A Season is made of two parts, (1) the primary year and (2) a term which defines a segment of the year. This term could be a traditional season, like "Spring" or "Summer", or this term could be a month, like "May" or "June", or this could be an arbitrary season name which is meaningful to the breeding Program like "PlantingTime_3" or "Season E".
 */
CREATE TABLE brapi_Seasons (
  -- Primary properties
  seasonDbId STRING NOT NULL PRIMARY KEY COMMENT 'The ID which uniquely identifies a season. For backward compatibility it can be a string like ''2012'', ''1957-2004''',
  seasonName STRING PRIMARY KEY COMMENT 'Name of the season. ex. ''Spring'', ''Q2'', ''Season A'', etc.',
  -- Clustering properties
  year INT COMMENT 'The 4 digit year of the season.'
) 
COMMENT 'A Season defines a period in time. A Season is made of two parts, (1) the primary year and (2) a term which defines a segment of the year. This term could be a traditional season, like "Spring" or "Summer", or this term could be a month, like "May" or "June", or this could be an arbitrary season name which is meaningful to the breeding Program like "PlantingTime_3" or "Season E".';


-- Generated by Schema Tools Generator Version: '0.65.0'
