-- SeedLotTransaction

/* 
The record of an event where material was moved in or out of a particular SeedLot
 */
CREATE TABLE brapi_SeedLotTransactions (
  -- Link properties
  fromSeedLotDbId STRING COMMENT 'The identifier for the Seed Lot being transferred out of. Unique DbId for the Seed Lot',
  fromSeedLotPUI STRING COMMENT 'The identifier for the Seed Lot being transferred out of',
  fromSeedLotName STRING COMMENT 'The identifier for the Seed Lot being transferred out of. A human readable name for this Seed Lot',
  toSeedLotDbId STRING COMMENT 'The identifier for the Seed Lot being transferred into. Unique DbId for the Seed Lot',
  toSeedLotPUI STRING COMMENT 'The identifier for the Seed Lot being transferred into',
  toSeedLotName STRING COMMENT 'The identifier for the Seed Lot being transferred into. A human readable name for this Seed Lot',
  -- Properties
  additionalInfo MAP<STRING,STRING> COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  amount DOUBLE COMMENT 'The number of units being transferred between SeedLots. Could be a count (seeds, bulbs, etc) or a weight (kg of seed).',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  transactionDbId STRING NOT NULL COMMENT 'Unique DbId for the Seed Lot Transaction',
  transactionDescription STRING COMMENT 'A general description of this Seed Lot Transaction',
  transactionTimestamp STRING COMMENT 'The time stamp for when the transaction occurred',
  units STRING COMMENT 'A description of the things being transferred between SeedLots in a transaction (seeds, bulbs, kg, etc)'
) 
COMMENT 'The record of an event where material was moved in or out of a particular SeedLot';


-- Generated by Schema Tools Generator Version: '0.77.0'
