-- Trait

/* 
A Trait describes what property is being observed. 
<br>For example, an ObservationVariable might be defined with a Trait of "plant height", a Scale of "meters", and a Method of "tape measure". This variable would be distinct from a variable with the Trait "Leaf length" or "Flower height". 
 */
CREATE TABLE brapi_Traits (
  -- Primary properties
  traitDbId STRING PRIMARY KEY COMMENT 'The ID which uniquely identifies a trait',
  traitName STRING NOT NULL PRIMARY KEY COMMENT 'The human readable name of a trait <br/>MIAPPE V1.1 (DM-86) Trait - Name of the (plant or environmental) trait under observation',
  traitPUI STRING PRIMARY KEY COMMENT 'The Permanent Unique Identifier of a Trait, usually in the form of a URI',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  alternativeAbbreviations ARRAY<STRING> COMMENT 'A list of shortened, human readable, names for a Trait. These abbreviations are acceptable alternatives to the mainAbbreviation and do not need to follow any formatting convention.',
  attribute STRING COMMENT 'A trait can be decomposed as "Trait" = "Entity" + "Attribute", the attribute is the observed feature (or characteristic) of the entity e.g., for "grain colour", attribute = "colour"',
  attributePUI STRING COMMENT 'The Permanent Unique Identifier of a Trait Attribute, usually in the form of a URI <br/>A trait can be decomposed as "Trait" = "Entity" + "Attribute", the attribute is the observed feature (or characteristic) of the entity e.g., for "grain colour", attribute = "colour"',
  entity STRING COMMENT 'A trait can be decomposed as "Trait" = "Entity" + "Attribute", the entity is the part of the plant that the trait refers to e.g., for "grain colour", entity = "grain"',
  entityPUI STRING COMMENT 'The Permanent Unique Identifier of a Trait Entity, usually in the form of a URI <br/>A Trait can be decomposed as "Trait" = "Entity" + "Attribute", the Entity is the part of the plant that the trait refers to e.g., for "grain colour", entity = "grain" ',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  mainAbbreviation STRING COMMENT 'A shortened version of the human readable name for a Trait',
  ontologyReference 
    STRUCT<
      -- Primary properties
      ontologyReferenceDbId STRING COMMENT 'The ID which uniquely identifies a ontology reference',
      -- Link properties
      ontologyDbId STRING COMMENT 'Ontology database unique identifier',
      ontologyName STRING COMMENT 'Ontology name',
      -- Properties
      documentationLinks
        ARRAY<
          STRUCT<
            URL STRING COMMENT 'The URL or URI to the documentation',
            type STRING COMMENT 'The type of documentation, which can be OBO Foundry, an RDF term or a webpage.'
          >
        > COMMENT 'links to various ontology documentation',
      version STRING COMMENT 'Ontology version (no specific format)'
    > NOT NULL COMMENT 'MIAPPE V1.1  (DM-85) Variable accession number - Accession number of the variable in the Crop Ontology  (DM-87) Trait accession number - Accession number of the trait in a suitable controlled vocabulary (Crop Ontology, Trait Ontology).  (DM-89) Method accession number - Accession number of the method in a suitable controlled vocabulary (Crop Ontology, Trait Ontology).  (DM-93) Scale accession number - Accession number of the scale in a suitable controlled vocabulary (Crop Ontology).',
  status STRING COMMENT 'Trait status (examples: "recommended", "obsolete", "legacy", etc.)',
  synonyms ARRAY<STRING> COMMENT 'Other trait names',
  traitClass STRING COMMENT 'A classification to describe the type of trait and the context it should be considered in. <br/> examples- "morphological", "phenological", "agronomical", "physiological", "abiotic stress", "biotic stress", "biochemical", "quality traits", "fertility", etc.',
  traitDescription STRING COMMENT 'The description of a trait'
) 
COMMENT 'A Trait describes what property is being observed.  <br>For example, an ObservationVariable might be defined with a Trait of "plant height", a Scale of "meters", and a Method of "tape measure". This variable would be distinct from a variable with the Trait "Leaf length" or "Flower height". ';


-- Generated by Schema Tools Generator Version: '0.65.0'
