-- VarietyAttributeValue

/* 
TODO Description for VarietyAttributeValue
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_variety_attribute_values (
  attributeValueDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies this attribute value within the given database server',
  attributeValuePUI STRING PRIMARY KEY COMMENT 'The Permanent Unique Identifier of an Attribute Value, usually in the form of a URI',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  attributePUI STRING NOT NULL COMMENT 'The Permanent Unique Identifier of an Attribute, usually in the form of a URI',
  determinedDate STRING COMMENT 'The date the value of this attribute was determined for a given germplasm',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  value STRING COMMENT 'The value of this attribute for a given entity',
  varietyPUI STRING NOT NULL COMMENT 'The Permanent Unique Identifier which represents a variety'
) 
USING delta
CLUSTER BY (determinedDate)
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'TODO Description for VarietyAttributeValue';


-- Generated by Schema Tools Generator Version: '0.60.0'
