-- VarietyStage

/* 
TODO Description for VarietyStage
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_variety_stages (
  varietyStageDbId STRING NOT NULL PRIMARY KEY COMMENT 'The ID which uniquely identifies a variety stage within the given database server.',
  varietyStageName STRING NOT NULL COMMENT 'Name of the stage. It can be the preferred name and does not have to be unique.',
  commonCropName STRING NOT NULL COMMENT 'Common name for the crop associated with this stage.',
  cropPUI STRING NOT NULL COMMENT 'A permanent unique identifier associated with this Crop. For example, a URI or DOI',
  order INT NOT NULL COMMENT 'The relative order of the stage with other stages in this crop and variety type, starting with 0.',
  varietyStageDescription STRING NOT NULL COMMENT 'The description of the stage.',
  varietyType STRING NOT NULL COMMENT 'Type of variety which can be one of the following:   Hybrid   Parental line   Open Pollinated'
) 
USING delta
CLUSTER BY (commonCropName)
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'TODO Description for VarietyStage';


-- Generated by Schema Tools Generator Version: '0.60.0'
