-- Variety

/* 
The Variety module of Phenome will be adopted for pre-commercial lines and commercial lines.

# Field Crops

A variety will be a cultivar with variety advancement level (controlled by a workflow).
Variety Advancement Stages in FC:  NL-3, NL-2, NL-1 or PT0, PT1, PT2, PT3, PT4 or PYT, AYT

### Phenome Implementation
Variety is not supported for Phenome.

### PRISM Implementation
In Field Crops, a Variety is a PRISM Material which has started Material Advancement 
and has a Material Advancement Stage.

In Vegetable Crops, Variety is not supported.

###  Examples

TODO
 */
CREATE TABLE IF NOT EXISTS sta_dash.dadi_br_sandbox.silver_phenome_varieties (
  varietyDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies a variety within the given database server.',
  varietyName STRING NOT NULL COMMENT 'Name of the variety. It can be the preferred name and does not have to be unique.',
  varietyPUI STRING NOT NULL PRIMARY KEY COMMENT 'The Permanent Unique Identifier which represents a variety',
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'Additional arbitrary info',
  attributeValuePUIs ARRAY<STRING> COMMENT 'attributeValues',
  commonCropName STRING NOT NULL COMMENT 'Common name for the crop   MCPD (v2.1) (CROPNAME) 10. Common name of the crop. Example: "malting barley", "mas".',
  cropPUI STRING NOT NULL COMMENT 'A permanent unique identifier associated with this Crop. For example, a URI or DOI',
  cultivarPUI STRING NOT NULL COMMENT 'The Permanent Unique Identifier which represents a cultivar',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  synonyms
    ARRAY<
      STRUCT<
        synonym STRING NOT NULL COMMENT 'Alternative name or ID used to reference this variety',
        type STRING NOT NULL COMMENT 'A descriptive classification for this synonym. Can one of the following:   Alternative Name   Short Name   Old Name   Production Code   Pool Name   Genebank Material Name   ERP Code'
      >
    > NOT NULL COMMENT 'List of alternative names or IDs used to reference this variety',
  varietyStageDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies a variety stage within the given database server.',
  varietyStageHistory
    ARRAY<
      STRUCT<
        approverPUIs ARRAY<STRING> COMMENT 'The list of approvers for this change.',
        changeDate STRING NOT NULL COMMENT 'The time and date the status change was created.',
        requesterDbId STRING NOT NULL COMMENT 'Unique ID for a person',
        status STRING NOT NULL COMMENT 'The status of the change.',
        varietyStageDbId STRING NOT NULL COMMENT 'The ID which uniquely identifies a variety stage within the given database server.'
      >
    > COMMENT 'A list of all the stages the cultivar has progressed through, and those which are pending.',
  varietyType STRING NOT NULL COMMENT 'Type of variety which can be one of the following:   Fixed line   Hybrid   CMS   DH'
) 
USING delta
CLUSTER BY (commonCropName,varietyType)
TBLPROPERTIES ('delta.enableChangeDataFeed' = true)
COMMENT 'The Variety module of Phenome will be adopted for pre-commercial lines and commercial lines.  # Field Crops  A variety will be a cultivar with variety advancement level (controlled by a workflow). Variety Advancement Stages in FC:  NL-3, NL-2, NL-1 or PT0, PT1, PT2, PT3, PT4 or PYT, AYT  ### Phenome Implementation Variety is not supported for Phenome.  ### PRISM Implementation In Field Crops, a Variety is a PRISM Material which has started Material Advancement  and has a Material Advancement Stage.  In Vegetable Crops, Variety is not supported.  ###  Examples  TODO';


-- Generated by Schema Tools Generator Version: '0.60.0'
