-- Variant

/* 
A `Variant` represents a change in DNA sequence relative to some reference. For example, a variant could represent a classic marker, a SNP, or an insertion. This is equivalent to a row in VCF.
 */
CREATE TABLE brapi_Variants (
  -- Primary properties
  variantDbId STRING NOT NULL PRIMARY KEY COMMENT 'The ID which uniquely identifies a `Variant`',
  -- Link properties
  referenceDbId STRING NOT NULL COMMENT 'The unique identifier for a `Reference`',
  referenceName STRING NOT NULL COMMENT 'The human readable name of a `Reference` within a `ReferenceSet`.',
  referenceSetDbId STRING NOT NULL COMMENT 'The unique identifier for a ReferenceSet',
  referenceSetName STRING NOT NULL COMMENT 'The human readable name of a ReferenceSet',
  variantSetDbId STRING NOT NULL COMMENT 'The unique identifier for a VariantSet',
  variantSetName STRING COMMENT 'The human readable name for a VariantSet',
  -- Properties
  additionalInfo MAP<STRING,STRING> NOT NULL COMMENT 'A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.',
  analysis ARRAY<STRING> COMMENT 'Set of Analysis descriptors for this VariantSet',
  ciend ARRAY<INT> COMMENT 'Similar to "cipos", but for the variant''s end position (which is derived from start + svlen).',
  cipos ARRAY<INT> COMMENT 'In the case of structural variants, start and end of the variant may not be known with an exact base position. "cipos" provides an interval with high confidence for the start position. The interval is provided by 0 or 2 signed integers which are added to the start position. Based on the use in VCF v4.2',
  created STRING COMMENT 'The timestamp when this variant was created.',
  end INT COMMENT 'This field is optional and may be ignored if there is no relevant map or reference to be associated with. <br>The end position (exclusive), resulting in [start, end) closed-open interval. This is typically calculated  by `start + referenceBases.length`.',
  externalReferences
    ARRAY<
      STRUCT<
        referenceId STRING COMMENT 'The external reference ID. Could be a simple string or a URI.',
        referenceSource STRING COMMENT 'An identifier for the source system or database of this reference'
      >
    > COMMENT 'An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
  filtersApplied BOOLEAN COMMENT 'True if filters were applied for this variant. VCF column 7 "FILTER" any value other than the missing value.',
  filtersFailed ARRAY<STRING> COMMENT 'Zero or more filters that failed for this variant. VCF column 7 "FILTER" shared across all alleles in the same VCF record.',
  filtersPassed BOOLEAN COMMENT 'True if all filters for this variant passed. VCF column 7 "FILTER" value PASS.',
  referenceBases STRING COMMENT 'The reference bases for this variant. They start at the given start position.',
  start INT COMMENT 'This field is optional and may be ignored if there is no relevant map or reference to be associated with. <br> The start position at which this variant occurs (0-based). This corresponds to the first base of the string  of reference bases. Genomic positions are non-negative integers less than reference length. Variants spanning  the join of circular genomes are represented as two variants one on each side of the join (position 0).',
  svlen INT COMMENT 'Length of the - if labeled as such in variant_type - structural variation. Based on the use in VCF v4.2',
  updated STRING COMMENT 'The time at which this variant was last updated.',
  variantNames ARRAY<STRING> COMMENT 'A human readable name associated with a `Variant`',
  variantType STRING COMMENT 'The "variant_type" is used to denote e.g. structural variants. Examples:   DUP  : duplication of sequence following "start"   DEL  : deletion of sequence following "start"'
) 
COMMENT 'A `Variant` represents a change in DNA sequence relative to some reference. For example, a variant could represent a classic marker, a SNP, or an insertion. This is equivalent to a row in VCF.';


-- Generated by Schema Tools Generator Version: '0.60.0'
